apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kube-bundle-resources
  labels:
    app: test-kube-bundle-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kube-bundle-resources
  template:
    metadata:
      labels:
        app: test-kube-bundle-resources
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["sleep", "infinity"]
          ports:
            - containerPort: 8080
          env:
            - name: SHARED_CONFIG_MAP
              value: ${backend-system/shared-config-map-name}
            - name: EXTERNAL_NAMESPACE
              value: ${external-target-namespace}
