apiVersion: v1
kind: Service
metadata:
  name: test-kube-bundle-resources
spec:
  selector:
    app: test-kube-bundle-resources
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
